from sqlite3 import Cursor
from turtle import *

#1
# name = input()
# print('Welcome,', name, '!')

#2
# print('first name:')
# fname = input()
# print('last name:')
# lname = input()
# print('phone:')
# phone = input()
# print('Your registered name is', fname, lname)
# print('Your phone number is', phone)

#3
# print('Name \t \t : \t Banana')
# print('Birthdate \t : \t 3/6/2010')

#4
# print('What year is it?')
# year = input()
# print("\t \t  . : .\n \t \t '. : .' \n HAPPY NEW YEAR . '.:.' . \n", "!!!", year, "!!!   . .':'. . \n \t \t .' : '. \n \t \t  ' : '")

#5
# pensize(2)
# shape("turtle")
# forward(45)
# left(120)
# forward(90)
# left(120)
# forward(90)
# left(120)
# forward(45)
# left(90)
# mainloop()

#6
# shape('turtle')
# pensize(2)
# forward(90)
# left(90)
# forward(90)
# left(90)
# forward(90)
# left(90)
# forward(90)
# left(90)
# penup()
# setposition(-15, -15)
# pensize(3)
# pendown()
# forward(120)
# left(90)
# forward(120)
# left(90)
# forward(120)
# left(90)
# forward(120)
# left(90)
# penup()
# setposition(45, 45)
# left(90)
# mainloop()

#7
# shape('turtle')
# pensize(1)
# forward(90)
# left(90)
# forward(90)
# left(90)
# forward(90)
# left(90)
# forward(90)
# left(90)
# penup()
# setposition(45, -15)
# pendown()
# left(45)
# forward(90)
# left(90)
# forward(90)
# left(90)
# forward(90)
# left(90)
# forward(90)
# left(90)
# penup()
# setposition(45, 45)
# left(45)
# mainloop()